"use server";

import { BACKEND_URL } from "@/lib/config";
import { authenticatedBackendFetch } from "@/lib/server/backendClient";

type Result<T> = { success: true; data: T } | { success: false; code: string; message: string };
export type EvaluationEvidence = { fragmentId: string; sourceLabel: string; locator: Record<string, string | number>; content: string };
export type EvaluationView = {
  run: { runId: string; status: string; sealedPrice: boolean; assessmentCount: number; riskCount: number; questionCount: number; scoringPolicyVersion: string; createdAt: string };
  permission: { owner: boolean; assigned: boolean; canViewCommercial: boolean };
  assignment: null | { assignmentId: string; role: string; conflictStatus: "pending" | "clear" | "conflict" | "not_applicable"; conflictNote: string; status: string; version: number; criterionIds: string[]; complete: boolean; overallScore: number | null };
  criteria: Array<{ criterionId: string; key: string; name: string; description: string; weight: number; rubricMaximum: number; rubricAnchors: Array<{ score: number; label: string; description: string }>; priceVisibility: string; humanOnly: boolean; requirementIds: string[] }>;
  assessments: Array<{ assessmentId: string; requirementId: string; requirementTitle: string; mandatory: boolean; eligibility: boolean; verdict: string; rationale: string; confidence: number; needsHumanReview: boolean; reviewReasons: string[]; evidence: EvaluationEvidence[] }>;
  risks: Array<{ riskId: string; category: string; severity: "high" | "medium" | "low"; title: string; basis: string; question: string; evidence: EvaluationEvidence[] }>;
  commercial: null | { submittedTotal: number | null; submittedCurrency: string | null; comparable: boolean; normalizedTotal: number | null; normalizedCurrency: string | null; arithmeticStatus: string; assumptions: string[]; refusalCodes: string[]; policyVersion: string; lineItems: Array<{ category: string; description: string; amount: number | null; currency: string | null; optionOrExclusion: boolean }> };
  scores: Array<{ eventId: string; assignmentId: string; criterionId: string; eventType: string; score: number | null; rubricMaximum: number; criterionWeight: number; weightedContribution: number | null; rationale: string; evidenceFragmentIds: string[]; scoringPolicyVersion: string; createdAt: string }>;
  aggregates: Array<{ criterionId: string; submittedCount: number; assignedCount: number; mean: number | null; minimum: number | null; maximum: number | null; spread: number | null; meanWeightedContribution: number | null }>;
  assignments: Array<{ assignmentId: string; evaluatorUserId: string; role: string; conflictStatus: string; status: string; criterionIds: string[]; commercialAccess: string; complete: boolean; overallScore: number | null }>;
};

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const num = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const nullableNum = (value: unknown) => value === null || value === undefined ? null : Number.isFinite(Number(value)) ? Number(value) : null;
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const evidence = (value: unknown): EvaluationEvidence[] => (Array.isArray(value) ? value : []).flatMap((item) => {
  if (!isRecord(item) || typeof item.fragmentId !== "string") return [];
  const locator = isRecord(item.locator) ? Object.fromEntries(Object.entries(item.locator).filter((entry): entry is [string, string | number] => typeof entry[1] === "string" || typeof entry[1] === "number")) : {};
  return [{ fragmentId: item.fragmentId, sourceLabel: String(item.sourceLabel ?? "Evidence"), locator, content: String(item.content ?? "") }];
});
const rubricAnchors = (value: unknown) => (Array.isArray(value) ? value : []).flatMap((item) => isRecord(item) && typeof item.label === "string" && typeof item.description === "string" ? [{ score: num(item.score), label: item.label, description: item.description }] : []);
const parseView = (value: unknown): EvaluationView | null => {
  if (!isRecord(value) || !isRecord(value.run) || typeof value.run.runId !== "string" || !isRecord(value.permission)) return null;
  const run = value.run, permission = value.permission, assignment = isRecord(value.assignment) ? value.assignment : null;
  return {
    run: { runId: String(run.runId), status: String(run.status ?? ""), sealedPrice: run.sealedPrice === true, assessmentCount: num(run.assessmentCount), riskCount: num(run.riskCount), questionCount: num(run.questionCount), scoringPolicyVersion: String(run.scoringPolicyVersion ?? ""), createdAt: String(run.createdAt ?? "") },
    permission: { owner: permission.owner === true, assigned: permission.assigned === true, canViewCommercial: permission.canViewCommercial === true },
    assignment: assignment && typeof assignment.assignmentId === "string" ? { assignmentId: assignment.assignmentId, role: String(assignment.role ?? ""), conflictStatus: assignment.conflictStatus === "clear" || assignment.conflictStatus === "conflict" || assignment.conflictStatus === "not_applicable" ? assignment.conflictStatus : "pending", conflictNote: String(assignment.conflictNote ?? ""), status: String(assignment.status ?? ""), version: num(assignment.version), criterionIds: strings(assignment.criterionIds), complete: assignment.complete === true, overallScore: nullableNum(assignment.overallScore) } : null,
    criteria: (Array.isArray(value.criteria) ? value.criteria : []).flatMap((item) => isRecord(item) && typeof item.criterionId === "string" ? [{ criterionId: item.criterionId, key: String(item.key ?? ""), name: String(item.name ?? "Criterion"), description: String(item.description ?? ""), weight: num(item.weight), rubricMaximum: num(item.rubricMaximum), rubricAnchors: rubricAnchors(item.rubricAnchors), priceVisibility: String(item.priceVisibility ?? "reviewers"), humanOnly: item.humanOnly === true, requirementIds: strings(item.requirementIds) }] : []),
    assessments: (Array.isArray(value.assessments) ? value.assessments : []).flatMap((item) => isRecord(item) && typeof item.assessmentId === "string" ? [{ assessmentId: item.assessmentId, requirementId: String(item.requirementId ?? ""), requirementTitle: String(item.requirementTitle ?? "Requirement"), mandatory: item.mandatory === true, eligibility: item.eligibility === true, verdict: String(item.verdict ?? "not_assessable"), rationale: String(item.rationale ?? ""), confidence: num(item.confidence), needsHumanReview: item.needsHumanReview === true, reviewReasons: strings(item.reviewReasons), evidence: evidence(item.evidence) }] : []),
    risks: (Array.isArray(value.risks) ? value.risks : []).flatMap((item) => isRecord(item) && typeof item.riskId === "string" ? [{ riskId: item.riskId, category: String(item.category ?? ""), severity: item.severity === "high" || item.severity === "medium" ? item.severity : "low", title: String(item.title ?? "Risk"), basis: String(item.basis ?? ""), question: String(item.question ?? ""), evidence: evidence(item.evidence) }] : []),
    commercial: isRecord(value.commercial) ? { submittedTotal: nullableNum(value.commercial.submittedTotal), submittedCurrency: typeof value.commercial.submittedCurrency === "string" ? value.commercial.submittedCurrency : null, comparable: value.commercial.comparable === true, normalizedTotal: nullableNum(value.commercial.normalizedTotal), normalizedCurrency: typeof value.commercial.normalizedCurrency === "string" ? value.commercial.normalizedCurrency : null, arithmeticStatus: String(value.commercial.arithmeticStatus ?? ""), assumptions: strings(value.commercial.assumptions), refusalCodes: strings(value.commercial.refusalCodes), policyVersion: String(value.commercial.policyVersion ?? ""), lineItems: (Array.isArray(value.commercial.lineItems) ? value.commercial.lineItems : []).flatMap((item) => isRecord(item) ? [{ category: String(item.category ?? ""), description: String(item.description ?? ""), amount: nullableNum(item.amount), currency: typeof item.currency === "string" ? item.currency : null, optionOrExclusion: item.optionOrExclusion === true }] : []) } : null,
    scores: (Array.isArray(value.scores) ? value.scores : []).flatMap((item) => isRecord(item) && typeof item.eventId === "string" ? [{ eventId: item.eventId, assignmentId: String(item.assignmentId ?? ""), criterionId: String(item.criterionId ?? ""), eventType: String(item.eventType ?? ""), score: nullableNum(item.score), rubricMaximum: num(item.rubricMaximum), criterionWeight: num(item.criterionWeight), weightedContribution: nullableNum(item.weightedContribution), rationale: String(item.rationale ?? ""), evidenceFragmentIds: strings(item.evidenceFragmentIds), scoringPolicyVersion: String(item.scoringPolicyVersion ?? ""), createdAt: String(item.createdAt ?? "") }] : []),
    aggregates: (Array.isArray(value.aggregates) ? value.aggregates : []).flatMap((item) => isRecord(item) && typeof item.criterionId === "string" ? [{ criterionId: item.criterionId, submittedCount: num(item.submittedCount), assignedCount: num(item.assignedCount), mean: nullableNum(item.mean), minimum: nullableNum(item.minimum), maximum: nullableNum(item.maximum), spread: nullableNum(item.spread), meanWeightedContribution: nullableNum(item.meanWeightedContribution) }] : []),
    assignments: (Array.isArray(value.assignments) ? value.assignments : []).flatMap((item) => isRecord(item) && typeof item.assignmentId === "string" ? [{ assignmentId: item.assignmentId, evaluatorUserId: String(item.evaluatorUserId ?? ""), role: String(item.role ?? ""), conflictStatus: String(item.conflictStatus ?? ""), status: String(item.status ?? ""), criterionIds: strings(item.criterionIds), commercialAccess: String(item.commercialAccess ?? ""), complete: item.complete === true, overallScore: nullableNum(item.overallScore) }] : []),
  };
};
const base = (proposalId: string, submissionId: string, versionId: string) => `/api/v1/proposals/${encodeURIComponent(proposalId)}/intelligence/submissions/${encodeURIComponent(submissionId)}/versions/${encodeURIComponent(versionId)}`;
const safe: Record<string, string> = { EVALUATION_RUN_NOT_FOUND: "No evaluation snapshot exists for this response version.", INTELLIGENCE_RUN_NOT_READY: "Generate proposal intelligence before starting evaluation.", INTELLIGENCE_COVERAGE_INCOMPLETE: "Resolve each unavailable response source before scoring this vendor.", SCORING_MATRIX_NOT_CONFIRMED: "Approve a confirmed 100% evaluation matrix before starting evaluation.", CONFLICT_DECLARATION_REQUIRED: "Declare your conflict-of-interest status before submitting scores.", SCORE_CITATION_REQUIRED: "Cite vendor evidence before submitting this score.", SCORE_ALREADY_SUBMITTED: "This score is submitted and must be reopened before correction.", SEALED_PRICE_ACCESS_REQUIRED: "Commercial information is sealed until access is granted." };
const call = async <T,>(path: string, init: RequestInit | undefined, parse: (value: unknown) => T | null): Promise<Result<T>> => {
  try { const response = await authenticatedBackendFetch(`${BACKEND_URL}${path}`, { ...init, cache: "no-store", headers: { "X-Correlation-ID": crypto.randomUUID(), ...(init?.headers ?? {}) } }); const body = await response.json().catch(() => ({})) as Record<string, unknown>; if (!response.ok) { const code = String(body.code ?? `HTTP_${response.status}`); return { success: false, code, message: safe[code] ?? String(body.title ?? "Evaluation operation failed.") }; } const parsed = parse(body.data); return parsed ? { success: true, data: parsed } : { success: false, code: "INVALID_RESPONSE", message: "The evaluation service returned an unexpected response." }; } catch { return { success: false, code: "NETWORK_ERROR", message: "The evaluation service could not be reached." }; }
};
const event = (value: unknown) => isRecord(value) && typeof value.eventId === "string" ? { eventId: value.eventId } : null;
export const getLatestEvaluationAction = async (proposalId: string, submissionId: string, versionId: string) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs/latest`, undefined, parseView);
export const createEvaluationAction = async (proposalId: string, submissionId: string, versionId: string, sealedPrice: boolean) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ sealedPrice }) }, (value) => isRecord(value) && typeof value.runId === "string" ? { runId: value.runId } : null);
export const prepareAutomaticEvaluationAction = async (proposalId: string, submissionId: string, versionId: string) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs/automatic`, { method: "POST" }, parseView);
export const declareEvaluationConflictAction = async (proposalId: string, submissionId: string, versionId: string, runId: string, status: "clear" | "conflict", note: string, expectedVersion: number) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs/${encodeURIComponent(runId)}/conflict-declaration`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, note, expectedVersion }) }, (value) => isRecord(value) && typeof value.assignmentId === "string" ? { assignmentId: value.assignmentId } : null);
export const recordEvaluationScoreAction = async (proposalId: string, submissionId: string, versionId: string, runId: string, score: { criterionId: string; eventType: "draft" | "submitted" | "superseded"; score: number; rationale: string; evidenceFragmentIds: string[] }) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs/${encodeURIComponent(runId)}/score-events`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(score) }, event);
export const reopenEvaluationScoreAction = async (proposalId: string, submissionId: string, versionId: string, runId: string, assignmentId: string, criterionId: string, reason: string) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs/${encodeURIComponent(runId)}/score-events/reopen`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ assignmentId, criterionId, reason }) }, event);
export const setCommercialAccessAction = async (proposalId: string, submissionId: string, versionId: string, runId: string, assignmentId: string, decision: "granted" | "revoked", reason: string) => await call(`${base(proposalId, submissionId, versionId)}/evaluation-runs/${encodeURIComponent(runId)}/commercial-access-events`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ assignmentId, decision, reason }) }, event);
