"use server";

import { BACKEND_URL } from "@/lib/config";
import { authenticatedBackendFetch } from "@/lib/server/backendClient";

type Result<T> = { success: true; data: T } | { success: false; code: string; message: string };
export type ClarificationSet = { setId: string; setVersion: number; status: "draft" | "approved" | "dispatch_recorded"; manifestChecksum: string; contentChecksum: string; lockVersion: number; approvedAt: string | null; dispatchRecordedAt: string | null; createdAt: string; updatedAt: string; questions: Array<{ questionId: string; riskId: string; participantId: string; vendorLabel: string; question: string; disposition: "included" | "excluded"; ordinal: number }> };
export type IntelligenceAudit = {
  schemaVersion: string; runId: string; generatedAt: string; freshness: { state: "current" | "stale"; reasons: string[] };
  manifest: { content_checksum: string; proposal_version: string; proposal_checksum: string; requirement_set_version: number; requirement_checksum: string; matrix_version: number; matrix_checksum: string; price_visibility: string; created_at: string };
  events: Array<{ id: string; action: string; decision: string; reason: string | null; correlation_id: string; metadata: Record<string, unknown>; occurred_at: string }>;
  exports: Array<{ id: string; report_type: string; media_type: string; content_checksum: string; freshness_state: string; permission_snapshot: { viewCommercial: boolean }; byte_size: number; created_at: string }>;
  clarificationEvents: Array<{ id: string; event_type: string; payload: Record<string, unknown>; created_at: string; set_id: string; set_version: number }>;
  legalHoldEvents: Array<{ id: string; hold_id: string; action: "placed" | "released"; reason: string; created_at: string }>;
  retentionPolicy: { procurement_record_retention_days: number; policy_basis: string; policy_version: string; version: number; updated_at: string | null };
};
export type IntelligenceOperations = { schemaVersion: string; runId: string; status: string; progress: number; freshnessState: string; durationMs: number | null; report_export_count: number; decision_count: number; clarification_set_count: number; approved_clarification_count: number; failed_job_count: number; participant_warning_count: number; unresolved_review_count: number; active_legal_hold_count: number };
export type IntelligenceOperationsBundle = { audit: IntelligenceAudit; operations: IntelligenceOperations; clarifications: ClarificationSet[] };

const record = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const nullableString = (value: unknown) => typeof value === "string" ? value : null;
const parseClarification = (value: unknown): ClarificationSet | null => {
  if (!record(value) || typeof value.setId !== "string" || !["draft", "approved", "dispatch_recorded"].includes(String(value.status)) || !Array.isArray(value.questions)) return null;
  const questions = value.questions.flatMap((item) => record(item) && typeof item.questionId === "string" && typeof item.question === "string" && ["included", "excluded"].includes(String(item.disposition)) ? [{ questionId: item.questionId, riskId: String(item.riskId ?? ""), participantId: String(item.participantId ?? ""), vendorLabel: String(item.vendorLabel ?? "Vendor"), question: item.question, disposition: item.disposition as "included" | "excluded", ordinal: number(item.ordinal) }] : []);
  return { setId: value.setId, setVersion: number(value.setVersion), status: value.status as ClarificationSet["status"], manifestChecksum: String(value.manifestChecksum ?? ""), contentChecksum: String(value.contentChecksum ?? ""), lockVersion: number(value.lockVersion), approvedAt: nullableString(value.approvedAt), dispatchRecordedAt: nullableString(value.dispatchRecordedAt), createdAt: String(value.createdAt ?? ""), updatedAt: String(value.updatedAt ?? ""), questions };
};
const parseAudit = (value: unknown): IntelligenceAudit | null => {
  if (!record(value) || typeof value.runId !== "string" || !record(value.freshness) || !record(value.manifest) || !record(value.retentionPolicy)) return null;
  const freshness = value.freshness, manifest = value.manifest, policy = value.retentionPolicy;
  return {
    schemaVersion: String(value.schemaVersion ?? ""), runId: value.runId, generatedAt: String(value.generatedAt ?? ""), freshness: { state: freshness.state === "stale" ? "stale" : "current", reasons: strings(freshness.reasons) },
    manifest: { content_checksum: String(manifest.content_checksum ?? ""), proposal_version: String(manifest.proposal_version ?? ""), proposal_checksum: String(manifest.proposal_checksum ?? ""), requirement_set_version: number(manifest.requirement_set_version), requirement_checksum: String(manifest.requirement_checksum ?? ""), matrix_version: number(manifest.matrix_version), matrix_checksum: String(manifest.matrix_checksum ?? ""), price_visibility: String(manifest.price_visibility ?? ""), created_at: String(manifest.created_at ?? "") },
    events: (Array.isArray(value.events) ? value.events : []).flatMap((item) => record(item) && typeof item.id === "string" ? [{ id: item.id, action: String(item.action ?? ""), decision: String(item.decision ?? ""), reason: nullableString(item.reason), correlation_id: String(item.correlation_id ?? ""), metadata: record(item.metadata) ? item.metadata : {}, occurred_at: String(item.occurred_at ?? "") }] : []),
    exports: (Array.isArray(value.exports) ? value.exports : []).flatMap((item) => record(item) && typeof item.id === "string" ? [{ id: item.id, report_type: String(item.report_type ?? ""), media_type: String(item.media_type ?? ""), content_checksum: String(item.content_checksum ?? ""), freshness_state: String(item.freshness_state ?? ""), permission_snapshot: record(item.permission_snapshot) ? { viewCommercial: item.permission_snapshot.viewCommercial === true } : { viewCommercial: false }, byte_size: number(item.byte_size), created_at: String(item.created_at ?? "") }] : []),
    clarificationEvents: (Array.isArray(value.clarificationEvents) ? value.clarificationEvents : []).flatMap((item) => record(item) && typeof item.id === "string" ? [{ id: item.id, event_type: String(item.event_type ?? ""), payload: record(item.payload) ? item.payload : {}, created_at: String(item.created_at ?? ""), set_id: String(item.set_id ?? ""), set_version: number(item.set_version) }] : []),
    legalHoldEvents: (Array.isArray(value.legalHoldEvents) ? value.legalHoldEvents : []).flatMap((item) => record(item) && typeof item.id === "string" && ["placed", "released"].includes(String(item.action)) ? [{ id: item.id, hold_id: String(item.hold_id ?? ""), action: item.action as "placed" | "released", reason: String(item.reason ?? ""), created_at: String(item.created_at ?? "") }] : []),
    retentionPolicy: { procurement_record_retention_days: number(policy.procurement_record_retention_days), policy_basis: String(policy.policy_basis ?? ""), policy_version: String(policy.policy_version ?? ""), version: number(policy.version), updated_at: nullableString(policy.updated_at) },
  };
};
const parseOperations = (value: unknown): IntelligenceOperations | null => {
  if (!record(value) || typeof value.runId !== "string") return null;
  return { schemaVersion: String(value.schemaVersion ?? ""), runId: value.runId, status: String(value.status ?? ""), progress: number(value.progress), freshnessState: String(value.freshnessState ?? ""), durationMs: value.durationMs === null ? null : number(value.durationMs), report_export_count: number(value.report_export_count), decision_count: number(value.decision_count), clarification_set_count: number(value.clarification_set_count), approved_clarification_count: number(value.approved_clarification_count), failed_job_count: number(value.failed_job_count), participant_warning_count: number(value.participant_warning_count), unresolved_review_count: number(value.unresolved_review_count), active_legal_hold_count: number(value.active_legal_hold_count) };
};
const safe: Record<string, string> = { CLARIFICATION_QUESTIONS_EMPTY: "No clarification candidates are available, or no questions are included.", CLARIFICATION_SET_FROZEN: "This clarification set is approved and cannot be edited.", CLARIFICATION_NOT_APPROVED: "Approve the clarification set before recording dispatch.", INPUT_VERSION_CONFLICT: "This record changed. Refresh and try again.", RETENTION_POLICY_INVALID: "Use a retention period from 365 to 3,650 days and document its basis.", LEGAL_HOLD_REASON_REQUIRED: "Provide a legal hold reason of at least 20 characters." };
const call = async <T,>(path: string, init: RequestInit | undefined, parse: (value: unknown) => T | null): Promise<Result<T>> => {
  try { const response = await authenticatedBackendFetch(`${BACKEND_URL}${path}`, { ...init, cache: "no-store", headers: { "X-Correlation-ID": crypto.randomUUID(), ...(init?.headers ?? {}) } }); const body = await response.json().catch(() => ({})) as Record<string, unknown>; if (!response.ok) { const code = String(body.code ?? `HTTP_${response.status}`); return { success: false, code, message: safe[code] ?? String(body.title ?? "Proposal intelligence operation failed.") }; } const parsed = parse(body.data); return parsed ? { success: true, data: parsed } : { success: false, code: "INVALID_RESPONSE", message: "The proposal intelligence service returned an unexpected response." }; } catch { return { success: false, code: "NETWORK_ERROR", message: "The proposal intelligence service could not be reached." }; }
};
const base = (proposalId: string, runId: string) => `/api/v1/proposals/${encodeURIComponent(proposalId)}/intelligence/comparisons/${encodeURIComponent(runId)}`;

export const getIntelligenceOperationsBundleAction = async (proposalId: string, runId: string): Promise<Result<IntelligenceOperationsBundle>> => {
  const [audit, operations, clarifications] = await Promise.all([
    call(`${base(proposalId, runId)}/audit`, undefined, parseAudit),
    call(`${base(proposalId, runId)}/operations`, undefined, parseOperations),
    call(`${base(proposalId, runId)}/clarification-sets`, undefined, (value) => Array.isArray(value) ? value.flatMap((item) => parseClarification(item) ?? []) : null),
  ]);
  if (!audit.success) return audit; if (!operations.success) return operations; if (!clarifications.success) return clarifications;
  return { success: true, data: { audit: audit.data, operations: operations.data, clarifications: clarifications.data } };
};
export const createClarificationSetAction = async (proposalId: string, runId: string) => call(`${base(proposalId, runId)}/clarification-sets`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() } }, parseClarification);
export const updateClarificationQuestionAction = async (proposalId: string, runId: string, setId: string, questionId: string, lockVersion: number, input: { question: string; disposition: "included" | "excluded" }) => call(`${base(proposalId, runId)}/clarification-sets/${encodeURIComponent(setId)}/questions/${encodeURIComponent(questionId)}`, { method: "PATCH", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID(), "If-Match": `"${lockVersion}"` }, body: JSON.stringify(input) }, parseClarification);
export const approveClarificationSetAction = async (proposalId: string, runId: string, setId: string, lockVersion: number) => call(`${base(proposalId, runId)}/clarification-sets/${encodeURIComponent(setId)}/approve`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID(), "If-Match": `"${lockVersion}"` } }, parseClarification);
export const recordClarificationDispatchAction = async (proposalId: string, runId: string, setId: string, input: { channel: "email_campaign" | "manual"; externalReference: string; recipientCount: number }) => call(`${base(proposalId, runId)}/clarification-sets/${encodeURIComponent(setId)}/record-dispatch`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(input) }, parseClarification);
export const updateIntelligenceRetentionPolicyAction = async (proposalId: string, runId: string, input: { retentionDays: number; policyBasis: string; expectedVersion: number }) => call(`${base(proposalId, runId)}/governance/retention-policy`, { method: "PUT", headers: { "Content-Type": "application/json", "If-Match": `"${input.expectedVersion}"` }, body: JSON.stringify({ retentionDays: input.retentionDays, policyBasis: input.policyBasis }) }, (value) => record(value) && Number.isInteger(Number(value.version)) ? { version: number(value.version) } : null);
export const placeIntelligenceLegalHoldAction = async (proposalId: string, runId: string, reason: string) => call(`${base(proposalId, runId)}/governance/legal-holds`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ reason }) }, (value) => record(value) && typeof value.holdId === "string" ? { holdId: value.holdId } : null);
export const releaseIntelligenceLegalHoldAction = async (proposalId: string, runId: string, holdId: string, reason: string) => call(`${base(proposalId, runId)}/governance/legal-holds/${encodeURIComponent(holdId)}/release`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ reason }) }, (value) => record(value) && typeof value.holdId === "string" ? { holdId: value.holdId } : null);
